export type ComicItem = {
  addtime?: unknown
  alading?: number
  alias_name?: string
  app_click_count?: number
  app_day_click_count?: number
  app_month_click_count?: number
  app_week_click_count?: number
  authors?: string
  baidu_assistant?: number
  chapters_tbl?: string
  check?: number
  comic_py?: string
  comment_key?: string
  copyright?: number
  cover?: string
  day_click_count?: number
  description?: string
  device_show?: number
  direction?: number
  first_letter?: string
  grade?: number
  h5_url?: null
  has_comment_id?: number
  hidden?: number
  hot_hits?: number
  hot_search?: number
  id?: number
  introduction?: string
  is_checked?: number
  is_dmzj?: number
  is_force_app_whitescreen?: number
  is_lock?: number
  is_show_animation_list?: number
  islong?: number
  keywords?: string
  language?: string
  last_update_chapter_id?: number
  last_update_chapter_name?: string
  last_updatetime?: number
  mobile?: number
  month_add_num?: number
  month_click_count?: number
  myfcomic_comic_id?: number
  name?: string
  need_update?: number
  page_show_flag?: number
  publish?: null
  quality?: number
  readergroup?: string
  readergroup_tag_id?: number
  real_name?: string
  series?: string
  sogou?: number
  source?: string
  status?: string
  status_tag_id?: number
  sum_chapters?: number
  sum_source?: number
  token?: string
  token32?: string
  total_add_num?: number
  type?: null
  types?: string
  uid?: null
  update_notice?: string
  url?: string
  w_link?: 2
  week_add_num?: number
  week_click_count?: number
  zone?: string
  zone_link?: string
  zone_tag_id?: number
}